### PR TITLE
Experimental: Alternative approach to resource/property view UI buttons

### PR DESCRIPTION
**Pull request by mdelez**
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-549

### CODE REVIEW

**Review by flavens — COMMENTED** [review]
LGTM except that 2 e2e tests failed on my machine (ran it 3 times, same issues each time)
image

**Comment by mdelez** [comment]
> LGTM except that 2 e2e tests failed on my machine (ran it 3 times, same issues each time)

I suppose you are building with the "npm run build-lib-dev" command, try building with "npm run build-lib" and then run the e2e tests again

**Comment by flavens** [comment]
> > LGTM except that 2 e2e tests failed on my machine (ran it 3 times, same issues each time)
> 
> I suppose you are building with the "npm run build-lib-dev" command, try building with "npm run build-lib" and then run the e2e tests again

No, I ran `npm run build-lib` and then `npm run e2e`

**Comment by mdelez** [comment]
> > > LGTM except that 2 e2e tests failed on my machine (ran it 3 times, same issues each time)
> > 
> > 
> > I suppose you are building with the "npm run build-lib-dev" command, try building with "npm run build-lib" and then run the e2e tests again
> 
> No, I ran `npm run build-lib` and then `npm run e2e`

Most curious....for me, when I build with `npm run build-lib`, the e2e tests work

**Review by flavens — APPROVED** [review]

**Pull request merged**
