### PR TITLE
DSP-720 - upgrade to Angular 10 + estimation

### PR DESCRIPTION
**Pull request by flavens**
resolves [DSP-720](https://dasch.myjetbrains.com/youtrack/issue/DSP-720)

### CODE REVIEW

**Comment by flavens** [comment]
@tobiasschweizer in c73e78f, I have "fix" a failing test but I think this is not what you expect. Could you take a look at it?

**Comment by tobiasschweizer** [comment]
> @tobiasschweizer in [c73e78f](https://github.com/dasch-swiss/dsp-ui-lib/commit/c73e78f4fdf9113267a2fade80e4febd4141b63c), I have "fix" a failing test but I think this is not what you expect. Could you take a look at it?

sure thing!

**Comment by tobiasschweizer** [comment]
@flavens For some reason, the "no selection" does nor trigger anymore when selected first. 
I think this might be related to the way it is defined in the template:

```html
<mat-option [value]="null">no selection</mat-option>
```

I will check if there has been a change that could explain that.

**Comment by tobiasschweizer** [comment]
@flavens https://github.com/dasch-swiss/dsp-ui-lib/pull/190/commits/16236a42ffe3de34e0cc51df45bedb887c5e9167 fixes the issue

**Comment by flavens** [comment]
the merge of this PR will have to wait until dsp-js-lib is also working with Angular 10 and dsp-app can be updated soon as well

**Comment by tobiasschweizer** [comment]
> the merge of this PR will have to wait until dsp-js-lib is also working with Angular 10 and dsp-app can be updated soon as well

Yes, this is also what I thought. Also all the other apps that are using dsp-ui like BEOL. Maybe we could integrate that into our release process, what you think?

**Comment by tobiasschweizer** [comment]
@flavens Did you experience the same issues with npm that we had with the data adapter (https://dasch.myjetbrains.com/youtrack/issue/DSP-691)?

**Comment by flavens** [comment]
> @flavens Did you experience the same issues with npm that we had with the data adapter (https://dasch.myjetbrains.com/youtrack/issue/DSP-691)?

I get 2 warnings about `codelyzer@5.2.2` only

**Comment by tobiasschweizer** [comment]
> > @flavens Did you experience the same issues with npm that we had with the data adapter (https://dasch.myjetbrains.com/youtrack/issue/DSP-691)?
> 
> I get 2 warnings about `codelyzer@5.2.2` only

I guess it would be a good idea to compare dependencies among our different apps. They were created under different circumstances and updated several times.

**Pull request closed without merging**
