### PR TITLE
Main dsp-ui stylesheet to override mat-design

### PR DESCRIPTION
**Pull request by kilchenmann**
Resolve [490](https://dasch.myjetbrains.com/youtrack/issue/DSP-490)
Resolve [448](https://dasch.myjetbrains.com/youtrack/issue/DSP-448)

Btw I cleaned up some styles and the Readme in lib:
- We shouldn't define font-family on lib side. Especially not third-party fonts like Roboto. This should be up to app developer to define a general font. 
- To override mat-styles a user has to add the dsp-ui.scss to the app in angular.json. I updated the README. But in our test-app in this repo the path to the dsp-ui.scss file is different, because we do not have the lib in `node_modules` but in `dist` folder. This is why it looks different.

### CODE REVIEW

**Comment by mdelez** [comment]
> LGTM
> @tobiasschweizer can answer your questions:
> 
> * can we merge _viewer-child.scss with viewer-parent in one main viewer stylesheet?
> * can we merge _viewer-parent.scss with viewer-child in one main viewer stylesheet?

I made those 🙋‍♂️ I'll see if I can merge them into one

**Comment by mdelez** [comment]
> > LGTM
> > @tobiasschweizer can answer your questions:
> > 
> > * can we merge _viewer-child.scss with viewer-parent in one main viewer stylesheet?
> > * can we merge _viewer-parent.scss with viewer-child in one main viewer stylesheet?
> 
> I made those 🙋‍♂️ I'll see if I can merge them into one

@flavens yes we can merge them. You just need to make sure you update the imports for the scss files that are importing the viewer-child.scss

**Comment by kilchenmann** [comment]
> I'll see if I can merge them into one

If it's okay, I can do it in this PR...

**Comment by mdelez** [comment]
> > I'll see if I can merge them into one
> 
> If it's okay, I can do it in this PR...

I probably should've tagged you instead in my comment above. Combining them is fine :)

**Pull request merged**
