### PR TITLE
feat(advanced search): specify linked resource (DSP-1587)

### PR DESCRIPTION
**Pull request by tobiasschweizer**
resolves DSP-1587

TODOs:

- [x] distinguish between specifying a resource and searching by its label to get its IRI in `projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/specify-property-value.component.html` -> https://github.com/dasch-swiss/dsp-ui-lib/pull/293/commits/062875c0045ef18e32490c5c2a745b2efc1760b8
    - ~~[ ] form should be invalid unless the user specified at least one property on the linked resource~~ -> seems now unnecessary to me since this can behave like EXIST when no props are specified
    - [x] consider resource class restriction on linked resource
- [x] use knora-api:Resource as fallback for object class restriction on linking props  
- [x] make linked resource var unique using a call counter 
- [x] only allow sort criteria on top level
- [x] limit specification of linked resource to one level only (only main form and one additional level)
- [x] extend Gravsearch generation service so it can deal with linked resources

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@loicjaouen The best way to test this is using the playground app:
- http://localhost:4200/search (submits the queries to the local DSP-API instance -> you can search for actual data)
- http://localhost:4200/advanced-search (just produces Gravsearch)

**Comment by tobiasschweizer** [comment]
@kilchenmann I think I should document the comparison operators somewhere (user docs).
Could I add this to https://github.com/dasch-swiss/dsp-ui-lib/blob/b436a310a48a565e01c2511abdfa97252478db7f/docs/how-to-use/search/extended-search.md?

**Comment by kilchenmann** [comment]
> @kilchenmann I think I should document the comparison operators somewhere (user docs).
> Could I add this to https://github.com/dasch-swiss/dsp-ui-lib/blob/b436a310a48a565e01c2511abdfa97252478db7f/docs/how-to-use/search/extended-search.md?

Yes that would be good 👍

**Comment by tobiasschweizer** [comment]
@gautschr to test this in the playground app, follow these steps: https://dasch-swiss.github.io/dsp-ui-lib/how-to-contribute/#first-steps

Then you can access these two pages:
- http://localhost:4200/search (submits the queries to the local DSP-API instance -> you can search for actual data)
- http://localhost:4200/advanced-search (just produces Gravsearch)

**Comment by tobiasschweizer** [comment]
@flavens I tested it using the following scenario:

Anything:Thing -> another Thing -> matches (Anything:Thing -> Decimal number -> > 0.5)

Screenshot 2021-05-20 at 10 49 22

Then I added other props on the top level and also on the linked resource.

However, it is important to test it with a different ontology with some actual project data.
I'll try to test it with BEOL data rom the staging server.

**Comment by tobiasschweizer** [comment]
> > @kilchenmann I think I should document the comparison operators somewhere (user docs).
> > Could I add this to https://github.com/dasch-swiss/dsp-ui-lib/blob/b436a310a48a565e01c2511abdfa97252478db7f/docs/how-to-use/search/extended-search.md?
> 
> Yes that would be good 👍

Could it be that https://github.com/dasch-swiss/dsp-ui-lib/blob/b436a310a48a565e01c2511abdfa97252478db7f/docs/how-to-use/search/extended-search.md is outdated? Tge component is now called advanced search component, also the parameters do not fit. Wouldn't it be good to have an example that fits the screenshot too?

**Comment by tobiasschweizer** [comment]
I'll work on the user docs in DSP-1651

**Review by gautschr — APPROVED** [review]
It works, thank you! I tested it locally with two different sets of data.

**Comment by kilchenmann** [comment]
It works fine.
We have to think about the design, but this will be part of the next iteration, right? I will move the current mockup from Balsamiq to Figma.

Screen Shot 2021-05-21 at 08 43 59

**Review by kilchenmann — APPROVED** [review]

**Comment by kilchenmann** [comment]
> @kilchenmann @subotic The E2E test fails because of an authentication problem:
> 
> > Bad credentials
> > https://github.com/dasch-swiss/dsp-ui-lib/pull/293/checks?check_run_id=2636678076#step:3:52
> 
> Any idea what to do about this?

It seems that someone deleted the repository "dasch-swiss/dsp-ci-assets".

**Comment by tobiasschweizer** [comment]
> > @kilchenmann @subotic The E2E test fails because of an authentication problem:
> > > Bad credentials
> > > https://github.com/dasch-swiss/dsp-ui-lib/pull/293/checks?check_run_id=2636678076#step:3:52
> > 
> > 
> > Any idea what to do about this?
> 
> It seems that someone deleted the repository [dasch-swiss/dsp-ci-assets](https://github.com/dasch-swiss/dsp-ci-assets)

fixed in https://github.com/dasch-swiss/dsp-ui-lib/pull/296

**Comment by loicjaouen** [comment]
i didn't delve into the code but thanks to @tobiasschweizer instruction, was able to run a query on one of our set: request http://theatresdesociete.unil.ch/ : theatrical Representations based on a play by Molière:

advanced-search

advanced-search-result

**Review by loicjaouen — APPROVED** [review]
good to go for this round ;)

**Pull request merged**
