### PR TITLE
chore(search): move docs to dsp-app (DSP-1662)

### PR DESCRIPTION
**Pull request by tobiasschweizer**
resolves DSP-1662

### CODE REVIEW

**Comment by kilchenmann** [comment]
I don't think that you have to remove those files from the documentation. If someone is using the library only, s/he will need this documentation.

**Comment by tobiasschweizer** [comment]
> I don't think that you have to remove those files from the documentation. If someone is using the library only, s/he will need this documentation.

I thought it'd be good to avoid redundancy. Maybe there could be a link to the user docs?

**Comment by tobiasschweizer** [comment]
I leave this decision to you. You can also close this PR if you'd like to keep the files as they are.

**Comment by kilchenmann** [comment]
I suggest to keep the files

**Pull request closed without merging**
