### PR TITLE
feat(viewer): resolve geoname id and show name (DSP-1212)

### PR DESCRIPTION
**Pull request by tobiasschweizer**
resolves DSP-1212

This PR adds a service that resolves a geoname id.

@gautschr @kilchenmann I'd like to discuss whether and to what degree we could also implement the autocomplete functionality for creating / editing values (like in DSP-Tangoh). As for the backend, we decided not to reimplement the logic with hierarchical lists as it was implemented in SALSAH.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
As for the token (which is actually more of a username), I made a new entry in the config object. Any user of the app could see it in the network requests to geonames so I thought it does not make much sense to hide it ...

**Comment by gautschr** [comment]
Your suggested autocomplete functionality for creating / editing values would be very comfortable in cases where the data are modified or created. It would eliminate an intermediate time-consuming step where one has to go to geonames to search for the correct ID.

**Review by gautschr — APPROVED** [review]
Works perfectly!

**Comment by tobiasschweizer** [comment]
> Your suggested autocomplete functionality for creating / editing values would be very comfortable in cases where the data are modified or created. It would eliminate an intermediate time-consuming step where one has to go to geonames to search for the correct ID.

Ok, I can implement that functionality in a subsequent PR.

**Review by mdelez — CHANGES_REQUESTED** [review]
Should the name of the corresponding Geoname identifier be added to the delete confirmation popup?

Screen Shot 2021-06-16 at 15 23 52

**Comment by mdelez** [comment]
> > Should the name of the corresponding Geoname identifier be added to the delete confirmation popup?
> > Screen Shot 2021-06-16 at 15 23 52
> 
> Good question. Ideally, yes because the name would make it clear to the user what is going to be deleted.
> 
> In practice, there are two problems:
> 
> * the name is not contained in the `ReadValue` itself, but the `ConfirmationDialogComponent` deals with a `ReadValue`
> * the name is obtained asynchronously via the geoname API and displayed using the async pipe. So we don't really know when it's available and delegate this to Angular.
> 
> **EDIT**: the case of a color value is actually similar. The user sees the hex code but not the color ;-)

All good, no need to spend time on it in my mind

**Review by mdelez — APPROVED** [review]

**Pull request merged**
