### PR TITLE
Add missing regex variables

### PR DESCRIPTION
**Pull request by flavens**
resolves [DSP-525](https://dasch.myjetbrains.com/youtrack/issue/DSP-525)

### CODE REVIEW

**Comment by kilchenmann** [comment]
@flavens Does it make sense to add also the regexp ontology name?
`ONTOLOGYNAME_REGEX = /^(?![vV][0-9]|[0-9]|[\u00C0-\u017F]).[a-zA-Z0-9]+\S*$/;`

At the moment it's defined in ontology editor only...

**Comment by flavens** [comment]
> @flavens Does it make sense to add also the regexp ontology name?
> `ONTOLOGYNAME_REGEX = /^(?![vV][0-9]|[0-9]|[\u00C0-\u017F]).[a-zA-Z0-9]+\S*$/;`
> 
> At the moment it's defined in ontology editor only...

in which repo is the file where you use ONTOLOGYNAME_REGEX?

**Comment by kilchenmann** [comment]
> in which repo is the file where you use ONTOLOGYNAME_REGEX?

In dsp-app. It's part of the ontology editor ([#229](https://github.com/dasch-swiss/dsp-app/pull/229))

**Comment by flavens** [comment]
> In dsp-app. It's part of the ontology editor ([#229](https://github.com/dasch-swiss/dsp-app/pull/229)). But we can keep it there. No problem

If you think that we will use it in another project or it is useful for other projects, we can move it here.

**Comment by kilchenmann** [comment]
> If you think that we will use it in another project or it is useful for other projects, we can move it here.

Probably yes. It could be helpful. Because the ontology name has so many rules: https://docs.knora.org/03-apis/api-v2/knora-iris/#iris-for-ontologies-and-ontology-entities

**Comment by flavens** [comment]
> Probably yes. It could be helpful. Because the ontology name has so many rules: https://docs.knora.org/03-apis/api-v2/knora-iris/#iris-for-ontologies-and-ontology-entities

done in 38052e5

**Pull request merged**
