### PR TITLE
Update peer-dep for dsp-js lib

### PR DESCRIPTION
**Pull request by tobiasschweizer**
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-592

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@mdelez We forgot to adapt the version of dsp-js lib ...

**Comment by mdelez** [comment]
> @mdelez We forgot to adapt the version of dsp-js lib ...

I suppose next time we should wait for the js-lib to publish before publishing the ui-lib, otherwise I believe the tests will fail

**Comment by tobiasschweizer** [comment]
I just got a warning from npm i

**Review by mdelez — APPROVED** [review]

**Comment by tobiasschweizer** [comment]
@mdelez Would you mind doing another release and updating the compatibility matrix?

**Comment by mdelez** [comment]
> @mdelez Would you mind doing another release and updating the compatibility matrix?

yeah, no problem!

**Comment by tobiasschweizer** [comment]
@mdelez ok, merged :-)

**Pull request merged**
