### PR TITLE
Update to v13.0.0-rc.23

### PR DESCRIPTION
**Pull request by tobiasschweizer**

### CODE REVIEW

**Comment by kilchenmann** [comment]
Why not updating to rc.24?

**Comment by tobiasschweizer** [comment]
> Why not updating to rc.24?

because dsp-js is still at rc.23

**Comment by tobiasschweizer** [comment]
@kilchenmann I made https://github.com/dasch-swiss/dsp-js-lib/pull/262 to update to rc.24. Once we make a new release with that, we can update to rc.24 here too.

**Comment by kilchenmann** [comment]
ok

**Comment by tobiasschweizer** [comment]
could you approve it then ;-) ?

**Review by kilchenmann — APPROVED** [review]

**Pull request merged**
