### PR TITLE
docs: Update CHANGELOG

### PR DESCRIPTION
**Pull request by kilchenmann**
I forgot to update changelog in last release. In this PR I updated it with GREN.

### CODE REVIEW

**Review by flavens — APPROVED** [review]
LGTM but could you leave a note to explain why we skip rc6?

**Comment by kilchenmann** [comment]
> LGTM but could you leave a note to explain why we skip rc6?

Where should I add it? When we use gren to update CHANGELOG automatically, it will be overwritten. There’s anyway the question how to update CHANGELOG automatically in the future...

**Comment by kilchenmann** [comment]
@flavens This could be an idea, how we can keep the CHANGELOG file up to date: In each PR we should add the current PR information to the CHANGELOG file in the corresponding section and this template: `[#PR-Nr](PR URL) PR Title`
e.g. #179 docs: Update CHANGELOG

What do you think?

**Comment by flavens** [comment]
> @flavens This could be an idea, how we can keep the CHANGELOG file up to date: In each PR we should add the current PR information to the CHANGELOG file in the corresponding section and this template: `[#PR-Nr](PR URL) PR Title`
> e.g. #179 docs: Update CHANGELOG
> 
> What do you think?

yes, this is a good idea, but we will have to do it each time. I do not know if it will be the case...

**Comment by kilchenmann** [comment]
> yes, this is a good idea, but we will have to do it each time. I do not know if it will be the case...

No this is not the best idea. I think the one I sent you in the private chat could be better. An automated process to update CHANGELOG file with the CI actions script. I'm still looking for a good solution. But now I will merge this PR

**Pull request merged**
