### PR TITLE
Integrate Ckeditor into Property View

### PR DESCRIPTION
**Pull request by mdelez**
resolves [DSP-682](https://dasch.myjetbrains.com/youtrack/issue/DSP-682)

`ValueTypeService.isReadOnly` has a a second required param now: `isReadOnly(valueTypeOrClass: string, value: ReadValue): boolean`

### CODE REVIEW

**Comment by mdelez** [comment]
@tobiasschweizer here is what I have so far, including broken tests 😄

**Comment by tobiasschweizer** [comment]
TODOs:
- only show XML text value if it uses the standard mapping

**Comment by tobiasschweizer** [comment]
## Conversion fun:

```
"xmlTransform": {
    "http://rdfh.ch/standoff/mappings/StandardMapping": {
      "<hr>": "<hr/>",
      "</hr>": "",
      "<s>": "<strike>",
      "</s>": "</strike>",
      "<i>": "<em>",
      "</i>": "</em>",
      "<figure class=\"table\">": "",
      "</figure>": ""
    }
  }
```

**Comment by tobiasschweizer** [comment]
@mdelez Could you have a look at https://github.com/dasch-swiss/dsp-ui-lib/pull/199/commits/2627050a0c53ae422b1c08d2ec031f0aa456457d? I had to adapt some expectations in the tests.

**Comment by tobiasschweizer** [comment]
@mdelez I expanded the read-only check for XML values based on the mapping. However, this required a change in the value-type service's `isReadOnly` method. Is that ok? Since the service is provided in root, this is a breaking change.

**Comment by mdelez** [comment]
> @mdelez I expanded the read-only check for XML values based on the mapping. However, this required a change in the value-type service's `isReadOnly` method. Is that ok? Since the service is provided in root, this is a breaking change.
> 
> done in [598abb5](https://github.com/dasch-swiss/dsp-ui-lib/commit/598abb5c15f5efcb7ebc1d1a6b8af5d0d1309990)

Seems fine to me

**Comment by tobiasschweizer** [comment]
@mdelez awesome, I could add a new text!!!

**Review by tobiasschweizer — APPROVED** [review]

**Pull request merged**
